// resources/js/react/components/ui/navigation/NavUser.tsx
import LanguageSelector from '@/components/LanguageSelector';
import ThemeSelector from '@/components/ThemeSelector';
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar';
import {
    DropdownMenu,
    DropdownMenuContent,
    DropdownMenuGroup,
    DropdownMenuItem,
    DropdownMenuLabel,
    DropdownMenuSeparator,
    DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import {
    SidebarMenu,
    SidebarMenuButton,
    SidebarMenuItem,
    useSidebar,
} from '@/components/ui/sidebar';
import { useSettings } from '@/hooks/useSettings';
import { settingsHref } from '@/hooks/useSettingsModal';
import { useT } from '@/i18n';
import { handleAction } from '@/lib/navigation';
import type { User } from '@/types';
import type { MenuItem } from '@/types/navigation';
import { Link } from '@inertiajs/react';
import type { ComponentProps } from 'react';
import { ChevronsUpDown, UserCircle } from 'lucide-react';
import NavIcon from './NavIcon';

interface NavUserProps {
    user: User;
    items: MenuItem[];
}

/**
 * A menu entry's destination.
 *
 * A fragment-only URL stays a plain anchor. Inertia's `Link` calls
 * `preventDefault()` and writes history itself, so the browser never fires
 * `hashchange` — and anything listening for a fragment (the settings modal) would
 * never hear the URL change. It also spares a visit to a page we are already on.
 */
function NavLink({
    url,
    icon,
    title,
    ...props
}: ComponentProps<'a'> & {
    url?: string | null;
    icon?: string | null;
    title: string;
}) {
    const children = (
        <>
            <NavIcon icon={icon} />
            <span>{title}</span>
        </>
    );

    // Spread what the menu item passes down. `DropdownMenuItem asChild` clones
    // this element to hand it the item's styling and behaviour, and a component
    // that keeps those props to itself renders unstyled.
    if (url?.startsWith('#')) {
        return (
            <a href={url} {...props}>
                {children}
            </a>
        );
    }

    // Cast: Inertia types `onClick` against `Element` where the anchor props say
    // `HTMLAnchorElement`. Same event, narrower target.
    return (
        <Link href={url ?? '#'} {...(props as ComponentProps<typeof Link>)}>
            {children}
        </Link>
    );
}

export default function NavUser({ user, items }: NavUserProps) {
    const { isMobile } = useSidebar();
    const t = useT();
    const settings = useSettings();

    /**
     * Every section is contributed by a module, so an installation with none has
     * an empty settings modal and no reason to offer the entry. The `settings`
     * route itself is core and always exists, so its presence proves nothing.
     */
    const hasSettingsSections = (settings.sections?.length ?? 0) > 0;

    const userInitials = user.name
        .split(' ')
        .map((word) => word.charAt(0).toUpperCase())
        .slice(0, 2)
        .join('');

    return (
        <SidebarMenu>
            <SidebarMenuItem>
                <DropdownMenu modal={false}>
                    <DropdownMenuTrigger asChild>
                        <SidebarMenuButton
                            data-testid="user-menu-trigger"
                            size="lg"
                            className="data-[state=open]:bg-sidebar-accent data-[state=open]:text-sidebar-accent-foreground"
                        >
                            <Avatar className="h-8 w-8 rounded-lg">
                                <AvatarImage
                                    src={user.avatar}
                                    alt={user.name}
                                />
                                <AvatarFallback className="rounded-lg">
                                    {userInitials}
                                </AvatarFallback>
                            </Avatar>
                            <div className="grid flex-1 text-left text-sm leading-tight">
                                <span className="truncate font-medium">
                                    {user.name}
                                </span>
                                <span className="truncate text-xs">
                                    {user.email}
                                </span>
                            </div>
                            <ChevronsUpDown className="ml-auto size-4" />
                        </SidebarMenuButton>
                    </DropdownMenuTrigger>
                    <DropdownMenuContent
                        className="w-(--radix-dropdown-menu-trigger-width) min-w-56 rounded-lg"
                        side={isMobile ? 'bottom' : 'right'}
                        align="end"
                        sideOffset={4}
                    >
                        <DropdownMenuLabel className="p-0 font-normal">
                            <div className="flex items-center gap-2 px-1 py-1.5 text-left text-sm">
                                <Avatar className="h-8 w-8 rounded-lg">
                                    <AvatarImage
                                        src={user.avatar}
                                        alt={user.name}
                                    />
                                    <AvatarFallback className="rounded-lg">
                                        {userInitials}
                                    </AvatarFallback>
                                </Avatar>
                                <div className="grid flex-1 text-left text-sm leading-tight">
                                    <span className="truncate font-semibold">
                                        {user.name}
                                    </span>
                                    <span className="truncate text-xs">
                                        {user.email}
                                    </span>
                                </div>
                            </div>
                        </DropdownMenuLabel>

                        {hasSettingsSections && (
                            <>
                                <DropdownMenuSeparator />
                                <DropdownMenuItem asChild>
                                    {/* A fragment, so settings open over the current page. */}
                                    <a
                                        href={settingsHref('profile')}
                                        data-testid="open-settings"
                                    >
                                        <UserCircle className="size-4" />
                                        {t('Profile')}
                                    </a>
                                </DropdownMenuItem>
                            </>
                        )}

                        <DropdownMenuSeparator />
                        <DropdownMenuGroup>
                            <LanguageSelector mode="submenu" />
                            <ThemeSelector mode="submenu" />
                        </DropdownMenuGroup>

                        {items.length > 0 && (
                            <>
                                <DropdownMenuSeparator />
                                <DropdownMenuGroup>
                                    {items.map((item) => (
                                        <DropdownMenuItem
                                            key={item.id ?? item.title}
                                            asChild={!item.action}
                                            data-testid={
                                                item.action
                                                    ? `nav-action-${item.action}`
                                                    : undefined
                                            }
                                            onClick={
                                                item.action
                                                    ? (e) =>
                                                          handleAction(
                                                              item.action!,
                                                              e as unknown as MouseEvent,
                                                          )
                                                    : undefined
                                            }
                                        >
                                            {item.action ? (
                                                <>
                                                    <NavIcon icon={item.icon} />
                                                    <span>{t(item.title)}</span>
                                                </>
                                            ) : (
                                                <NavLink
                                                    url={item.url}
                                                    icon={item.icon}
                                                    title={t(item.title)}
                                                />
                                            )}
                                        </DropdownMenuItem>
                                    ))}
                                </DropdownMenuGroup>
                            </>
                        )}
                    </DropdownMenuContent>
                </DropdownMenu>
            </SidebarMenuItem>
        </SidebarMenu>
    );
}

// resources/js/vue/components/ui/navigation/NavUser.vue
<script setup lang="ts">
import LanguageSelector from '@/components/LanguageSelector.vue';
import ThemeSelector from '@/components/ThemeSelector.vue';
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar';
import { Badge } from '@/components/ui/badge';
import {
    DropdownMenu,
    DropdownMenuContent,
    DropdownMenuGroup,
    DropdownMenuItem,
    DropdownMenuLabel,
    DropdownMenuSeparator,
    DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import NavigationIcon from '@/components/ui/navigation/NavIcon.vue';
import {
    SidebarMenu,
    SidebarMenuButton,
    SidebarMenuItem,
    useSidebar,
} from '@/components/ui/sidebar';
import { useSettings } from '@/composables/useSettings';
import { settingsHref } from '@/composables/useSettingsModal';
import { handleAction } from '@/lib/navigation';
import type { User } from '@/types';
import type { MenuBadge, MenuItem } from '@/types/navigation';
import { Link } from '@inertiajs/vue3';
import { computed } from 'vue';
import IconChevronsUpDown from '~icons/lucide/chevrons-up-down';
import IconUserCircle from '~icons/lucide/user-circle';

const props = defineProps<{
    user: User;
    items: MenuItem[];
}>();

const { isMobile } = useSidebar();
const settings = useSettings();

/**
 * Every section is contributed by a module, so an installation with none has an
 * empty settings modal and no reason to offer the entry. The `settings` route
 * itself is core and always exists, so its presence proves nothing.
 */
const hasSettingsSections = computed(
    () => (settings.value.sections?.length ?? 0) > 0,
);

const userInitials = computed(() => {
    return props.user.name
        .split(' ')
        .map((word) => word.charAt(0).toUpperCase())
        .slice(0, 2)
        .join('');
});

// Helper function to get badge configuration for an item
function getBadgeConfig(item: MenuItem): MenuBadge | null {
    if (!item.badge) return null;

    // If badge is true, return simple dot configuration
    if (item.badge === true) {
        return { content: undefined };
    }

    // Otherwise return the badge object
    return item.badge as MenuBadge;
}

function handleClick(item: MenuItem, event: MouseEvent) {
    if (item.action) {
        handleAction(item.action, event);
    }
}
</script>

<template>
    <SidebarMenu>
        <SidebarMenuItem>
            <DropdownMenu :modal="false">
                <DropdownMenuTrigger as-child>
                    <SidebarMenuButton
                        data-testid="user-menu-trigger"
                        size="lg"
                        class="data-[state=open]:bg-sidebar-accent data-[state=open]:text-sidebar-accent-foreground"
                    >
                        <Avatar class="h-8 w-8 rounded-lg">
                            <AvatarImage :src="user.avatar" :alt="user.name" />
                            <AvatarFallback class="rounded-lg">
                                {{ userInitials }}
                            </AvatarFallback>
                        </Avatar>
                        <div
                            class="grid flex-1 text-left text-sm leading-tight"
                        >
                            <span class="truncate font-medium">
                                {{ user.name }}
                            </span>
                            <span class="truncate text-xs">
                                {{ user.email }}
                            </span>
                        </div>
                        <IconChevronsUpDown class="ml-auto size-4" />
                    </SidebarMenuButton>
                </DropdownMenuTrigger>
                <DropdownMenuContent
                    class="w-[--reka-dropdown-menu-trigger-width] min-w-56 rounded-lg"
                    :side="isMobile ? 'bottom' : 'right'"
                    align="end"
                    :side-offset="4"
                >
                    <DropdownMenuLabel class="p-0 font-normal">
                        <div
                            class="flex items-center gap-2 px-1 py-1.5 text-left text-sm"
                        >
                            <Avatar class="h-8 w-8 rounded-lg">
                                <AvatarImage
                                    :src="user.avatar"
                                    :alt="user.name"
                                />
                                <AvatarFallback class="rounded-lg">
                                    {{ userInitials }}
                                </AvatarFallback>
                            </Avatar>
                            <div
                                class="grid flex-1 text-left text-sm leading-tight"
                            >
                                <span class="truncate font-semibold">
                                    {{ user.name }}
                                </span>
                                <span class="truncate text-xs">
                                    {{ user.email }}
                                </span>
                            </div>
                        </div>
                    </DropdownMenuLabel>

                    <template v-if="hasSettingsSections">
                        <DropdownMenuSeparator />
                        <DropdownMenuItem as-child>
                            <!-- A fragment, so settings open over the current page. -->
                            <a
                                :href="settingsHref('profile')"
                                data-testid="open-settings"
                            >
                                <IconUserCircle class="size-4" />
                                {{ $t('Profile') }}
                            </a>
                        </DropdownMenuItem>
                    </template>

                    <DropdownMenuSeparator />

                    <!-- Fixed components (Language & Theme selectors) -->
                    <DropdownMenuGroup>
                        <LanguageSelector mode="submenu" />
                        <ThemeSelector mode="submenu" />
                    </DropdownMenuGroup>

                    <!-- Dynamic navigation items -->
                    <template v-if="items && items.length > 0">
                        <DropdownMenuSeparator />
                        <DropdownMenuGroup>
                            <DropdownMenuItem
                                v-for="item in items"
                                :key="item.id || item.title"
                                as-child
                                @click="
                                    item.action
                                        ? handleClick(item, $event)
                                        : undefined
                                "
                            >
                                <!-- Action button -->
                                <div
                                    v-if="item.action"
                                    :data-testid="`nav-action-${item.slug}`"
                                    :class="['cursor-pointer', item.class]"
                                >
                                    <NavigationIcon
                                        :icon="item.icon"
                                        :class="item.class && 'text-current'"
                                    />
                                    <span>{{ $t(item.title) }}</span>
                                    <Badge
                                        v-if="getBadgeConfig(item)"
                                        :variant="getBadgeConfig(item)?.variant"
                                        :class="getBadgeConfig(item)?.class"
                                        class="ml-auto"
                                    >
                                        <template
                                            v-if="getBadgeConfig(item)?.content"
                                        >
                                            {{ getBadgeConfig(item)?.content }}
                                        </template>
                                        <template v-else>
                                            <span
                                                class="size-1.5 rounded-xl bg-current"
                                            ></span>
                                        </template>
                                    </Badge>
                                </div>
                                <!--
                                    External links, and fragments: `Link` writes
                                    history itself, so no `hashchange` fires and
                                    the settings modal never hears the change.
                                -->
                                <a
                                    v-else-if="
                                        item.external === true ||
                                        item.url?.startsWith('#')
                                    "
                                    :href="item.url || '#'"
                                    :target="
                                        item.newPage ? '_blank' : undefined
                                    "
                                    :rel="
                                        item.newPage
                                            ? 'noopener noreferrer'
                                            : undefined
                                    "
                                    :class="item.class"
                                >
                                    <NavigationIcon
                                        :icon="item.icon"
                                        :class="item.class && 'text-current'"
                                    />
                                    <span>{{ $t(item.title) }}</span>
                                    <Badge
                                        v-if="getBadgeConfig(item)"
                                        :variant="getBadgeConfig(item)?.variant"
                                        :class="getBadgeConfig(item)?.class"
                                        class="ml-auto"
                                    >
                                        <template
                                            v-if="getBadgeConfig(item)?.content"
                                        >
                                            {{ getBadgeConfig(item)?.content }}
                                        </template>
                                        <template v-else>
                                            <span
                                                class="size-1.5 rounded-xl bg-current"
                                            ></span>
                                        </template>
                                    </Badge>
                                </a>
                                <!-- Internal Inertia link -->
                                <Link
                                    v-else
                                    :href="item.url || '#'"
                                    :target="
                                        item.newPage ? '_blank' : undefined
                                    "
                                    :class="item.class"
                                >
                                    <NavigationIcon
                                        :icon="item.icon"
                                        :class="item.class && 'text-current'"
                                    />
                                    <span>{{ $t(item.title) }}</span>
                                    <Badge
                                        v-if="getBadgeConfig(item)"
                                        :variant="getBadgeConfig(item)?.variant"
                                        :class="getBadgeConfig(item)?.class"
                                        class="ml-auto"
                                    >
                                        <template
                                            v-if="getBadgeConfig(item)?.content"
                                        >
                                            {{ getBadgeConfig(item)?.content }}
                                        </template>
                                        <template v-else>
                                            <span
                                                class="size-1.5 rounded-xl bg-current"
                                            ></span>
                                        </template>
                                    </Badge>
                                </Link>
                            </DropdownMenuItem>
                        </DropdownMenuGroup>
                    </template>
                </DropdownMenuContent>
            </DropdownMenu>
        </SidebarMenuItem>
    </SidebarMenu>
</template>
