// resources/js/components/ui/saucebase/ModuleModal.vue
<script setup lang="ts">
import { trans } from 'laravel-vue-i18n';
import { BookOpen, Check, Copy, Terminal, X } from '@lucide/vue';
import { onUnmounted, ref } from 'vue';
import { toast } from 'vue-sonner';
import type { Module } from './index';
import { useModules } from '@/composables/useModules';

const props = defineProps<{ selectedMod: Module | null }>();
const emit = defineEmits<{ close: [] }>();

const { has: isInstalled } = useModules();

const copied = ref(false);
let copyTimer: ReturnType<typeof setTimeout> | null = null;

function installCommand(mod: Module) {
    if (mod.id === 'custom')
        return 'php artisan saucebase:recipe MyAmazingModuleIdea';
    const composer = isInstalled(mod.id)
        ? `composer update saucebase/${mod.id}`
        : `composer require saucebase/${mod.id}`;
    return `${composer}\nphp artisan migrate\nphp artisan modules:seed --module=${mod.id}`;
}

function copyCommand() {
    if (!props.selectedMod) return;
    navigator.clipboard
        .writeText(installCommand(props.selectedMod))
        .then(() => {
            toast.success(trans('Copied to clipboard'));
            if (copyTimer) clearTimeout(copyTimer);
            copied.value = true;
            copyTimer = setTimeout(() => (copied.value = false), 2000);
        })
        .catch(() => toast.error(trans('Failed to copy')));
}

onUnmounted(() => {
    if (copyTimer) clearTimeout(copyTimer);
});
</script>

<template>
    <Teleport to="body">
        <Transition
            enter-active-class="transition-opacity duration-200"
            leave-active-class="transition-opacity duration-150"
            enter-from-class="opacity-0"
            leave-to-class="opacity-0"
        >
            <div
                v-if="selectedMod"
                class="bg-background/50 fixed inset-0 z-50 backdrop-blur-md"
                @click="emit('close')"
            />
        </Transition>

        <Transition
            enter-active-class="transition-all duration-300 ease-out"
            leave-active-class="transition-all duration-200 ease-in"
            enter-from-class="opacity-0 translate-y-6 scale-[0.96]"
            leave-to-class="opacity-0 translate-y-4 scale-[0.97]"
        >
            <div
                v-if="selectedMod"
                class="pointer-events-none fixed inset-0 z-50 flex items-center justify-center p-6 shadow-lg"
            >
                <div
                    class="pointer-events-auto relative w-full max-w-xl"
                    @click.stop
                >
                    <!-- Modal card body -->
                    <div
                        class="bg-card/90 border-border relative z-10 flex flex-col gap-3 rounded-xl border p-6 shadow-[0px_5px_0_0_color-mix(in_oklch,var(--color-white)_85%,black)] dark:shadow-[0px_5px_0_0_color-mix(in_oklch,var(--color-white)_20%,black)]"
                        :style="{ '--mod-color': `var(${selectedMod.color})` }"
                    >
                        <!-- Close button -->
                        <button
                            class="text-muted-foreground hover:text-foreground hover:border-foreground absolute top-3 right-3 z-20 cursor-pointer rounded-full border p-1.5 transition-colors"
                            @click="emit('close')"
                        >
                            <X class="size-4" />
                        </button>

                        <slot name="before" />

                        <!-- Header: icon + title -->
                        <div class="flex items-center gap-3">
                            <div
                                class="flex size-11 shrink-0 items-center justify-center rounded-full"
                                :style="{
                                    background: `var(${selectedMod.color})`,
                                }"
                            >
                                <component
                                    :is="selectedMod.icon"
                                    class="size-5 text-white"
                                    aria-hidden="true"
                                />
                            </div>
                            <div class="flex flex-1 flex-wrap items-center gap-2">
                                <h2
                                    class="text-foreground text-xl leading-tight font-bold"
                                >
                                    {{ selectedMod.title() }}
                                </h2>
                                <span
                                    v-if="isInstalled(selectedMod.id)"
                                    class="border-primary text-primary rounded-full border px-3 text-sm ml-2 py-1 font-semibold"
                                >
                                    {{ $t('Installed') }}
                                </span>
                            </div>
                        </div>

                        <!-- Description -->
                        <p class="text-muted-foreground py-2 leading-relaxed">
                            {{ selectedMod.description() }}
                        </p>

                        <!-- Features checklist -->
                        <ul
                            class="grid grid-cols-2 gap-x-4 gap-y-1.5 rounded-sm border p-4"
                        >
                            <li
                                v-for="feature in selectedMod.features"
                                :key="feature()"
                                class="text-foreground flex items-center gap-2 text-sm"
                            >
                                <Check
                                    class="size-3.5 shrink-0"
                                    style="color: var(--mod-color)"
                                    aria-hidden="true"
                                />
                                {{ feature() }}
                            </li>
                        </ul>

                        <!-- Install command (free + custom only) -->
                        <div
                            v-if="selectedMod.href !== null"
                            class="mt-2 flex flex-col gap-2"
                        >
                            <div
                                class="flex items-center gap-3 rounded-xl bg-gray-950 px-4 py-3 shadow-sm dark:bg-gray-900"
                            >
                                <Terminal
                                    class="size-4 shrink-0 self-start mt-0.5 text-gray-500"
                                    aria-hidden="true"
                                />
                                <code class="flex-1 whitespace-pre text-sm text-green-400">{{ installCommand(selectedMod) }}</code>
                                <button
                                    class="cursor-pointer self-start text-gray-300 transition-colors hover:text-gray-300"
                                    @click="copyCommand"
                                >
                                    <Check
                                        v-if="copied"
                                        class="size-4 text-green-400"
                                    />
                                    <Copy v-else class="size-4" />
                                </button>
                            </div>
                            <p
                                v-if="selectedMod.id !== 'custom'"
                                class="text-muted-foreground py-1 text-center text-sm"
                            >
                                {{
                                    $t(
                                        'This module may require additional steps after installation, check the docs',
                                    )
                                }}
                            </p>
                        </div>

                        <!-- CTA -->
                        <div class="-mx-6 border-t px-6 pt-4">
                            <a
                                v-if="selectedMod.href !== null"
                                :href="selectedMod.href"
                                target="_blank"
                                rel="noopener noreferrer"
                                class="flex w-full items-center justify-center gap-2 rounded-full px-6 py-2.5 text-sm font-semibold text-white shadow-[0_5px_0_0_color-mix(in_oklch,var(--mod-color)_85%,black)] transition-all duration-200 hover:-translate-y-0.5 hover:shadow-[0_7px_0_0_color-mix(in_oklch,var(--mod-color)_85%,black)]"
                                :style="{
                                    background: `var(${selectedMod.color})`,
                                }"
                            >
                                <BookOpen class="size-4" aria-hidden="true" />
                                {{ $t('Read the Documentation') }}
                            </a>
                            <span
                                v-else
                                class="bg-muted/90 border-muted-foreground/20 text-muted-foreground flex w-full items-center justify-center gap-2 rounded-full border px-6 py-2.5 text-sm font-semibold"
                            >
                                {{ $t('Coming Soon') }}
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </Transition>
    </Teleport>
</template>

// resources/js/react/components/ui/saucebase/ModuleModal.tsx
import { useModules } from '@/hooks/useModules';
import { useT } from '@/i18n';
import { BookOpen, Check, Copy, Terminal, X } from 'lucide-react';
import { useCallback, useEffect, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import { toast } from 'sonner';
import type { Module } from './index';

interface ModuleModalProps {
    selectedMod: Module | null;
    onClose: () => void;
}

function installCommand(mod: Module, installed: boolean): string {
    if (mod.id === 'custom')
        return 'php artisan saucebase:recipe MyAmazingModuleIdea';
    const composer = installed
        ? `composer update saucebase/${mod.id}`
        : `composer require saucebase/${mod.id}`;
    return `${composer}\nphp artisan migrate\nphp artisan modules:seed --module=${mod.id}`;
}

export function ModuleModal({ selectedMod, onClose }: ModuleModalProps) {
    const t = useT();
    const { has: isInstalled } = useModules();
    const [copied, setCopied] = useState(false);
    const copyTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);

    // `mod` keeps the rendered module alive during the exit animation.
    // `isOpen` drives the CSS transitions (false = closed state / starting state).
    const [mod, setMod] = useState<Module | null>(null);
    const [isOpen, setIsOpen] = useState(false);
    const closeTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);
    const openRafRef = useRef<number | null>(null);

    useEffect(() => {
        if (selectedMod) {
            if (closeTimerRef.current) {
                clearTimeout(closeTimerRef.current);
                closeTimerRef.current = null;
            }
            setMod(selectedMod);
            // Double-raf ensures the element is in the DOM before the transition starts
            openRafRef.current = requestAnimationFrame(() => {
                openRafRef.current = requestAnimationFrame(() =>
                    setIsOpen(true),
                );
            });
        } else {
            if (openRafRef.current) {
                cancelAnimationFrame(openRafRef.current);
                openRafRef.current = null;
            }
            setIsOpen(false);
            // Wait for leave animation to finish before unmounting
            closeTimerRef.current = setTimeout(() => setMod(null), 300);
        }

        return () => {
            if (closeTimerRef.current) clearTimeout(closeTimerRef.current);
            if (openRafRef.current) cancelAnimationFrame(openRafRef.current);
        };
    }, [selectedMod]);

    useEffect(() => {
        return () => {
            if (copyTimerRef.current) clearTimeout(copyTimerRef.current);
        };
    }, []);

    const copyCommand = useCallback(() => {
        if (!mod) return;
        navigator.clipboard
            .writeText(installCommand(mod, isInstalled(mod.id)))
            .then(() => {
                toast.success(t('Copied to clipboard'));
                if (copyTimerRef.current) clearTimeout(copyTimerRef.current);
                setCopied(true);
                copyTimerRef.current = setTimeout(() => setCopied(false), 2000);
            })
            .catch(() => toast.error(t('Failed to copy')));
    }, [mod, t]);

    if (!mod) return null;

    const Icon = mod.icon;

    return createPortal(
        <>
            {/* Backdrop — enter 200ms, leave 150ms */}
            <div
                className="bg-background/50 fixed inset-0 z-50 backdrop-blur-md"
                style={{
                    opacity: isOpen ? 1 : 0,
                    transition: isOpen
                        ? 'opacity 200ms ease'
                        : 'opacity 150ms ease',
                    pointerEvents: isOpen ? undefined : 'none',
                }}
                onClick={onClose}
            />

            {/* Modal card — enter 300ms ease-out, leave 200ms ease-in */}
            <div
                className="pointer-events-none fixed inset-0 z-50 flex items-center justify-center p-6 shadow-lg"
                style={{
                    opacity: isOpen ? 1 : 0,
                    transform: isOpen
                        ? 'translateY(0) scale(1)'
                        : 'translateY(1.5rem) scale(0.96)',
                    transition: isOpen
                        ? 'opacity 300ms ease-out, transform 300ms ease-out'
                        : 'opacity 200ms ease-in, transform 200ms ease-in',
                }}
            >
                <div
                    className="pointer-events-auto relative w-full max-w-xl"
                    onClick={(e) => e.stopPropagation()}
                >
                    <div
                        className="bg-card/90 border-border relative z-10 flex flex-col gap-3 rounded-xl border p-6 shadow-[0px_5px_0_0_color-mix(in_oklch,var(--color-white)_85%,black)] dark:shadow-[0px_5px_0_0_color-mix(in_oklch,var(--color-white)_20%,black)]"
                        style={
                            {
                                '--mod-color': `var(${mod.color})`,
                            } as React.CSSProperties
                        }
                    >
                        {/* Close button */}
                        <button
                            className="text-muted-foreground hover:text-foreground hover:border-foreground absolute top-3 right-3 z-20 cursor-pointer rounded-full border p-1.5 transition-colors"
                            onClick={onClose}
                        >
                            <X className="size-4" />
                        </button>

                        {/* Header */}
                        <div className="flex items-center gap-3">
                            <div
                                className="flex size-11 shrink-0 items-center justify-center rounded-full"
                                style={{ background: `var(${mod.color})` }}
                            >
                                <Icon
                                    className="size-5 text-white"
                                    aria-hidden="true"
                                />
                            </div>
                            <div className="flex flex-1 flex-wrap items-center gap-2">
                                <h2 className="text-foreground text-xl leading-tight font-bold">
                                    {t(mod.title)}
                                </h2>
                                {isInstalled(mod.id) && (
                                    <span className="border-primary text-primary ml-2 rounded-full border px-3 py-1 text-sm font-semibold">
                                        {t('Installed')}
                                    </span>
                                )}
                            </div>
                        </div>

                        {/* Description */}
                        <p className="text-muted-foreground py-2 leading-relaxed">
                            {t(mod.description)}
                        </p>

                        {/* Features */}
                        <ul className="grid grid-cols-2 gap-x-4 gap-y-1.5 rounded-sm border p-4">
                            {mod.features.map((feature) => (
                                <li
                                    key={feature}
                                    className="text-foreground flex items-center gap-2 text-sm"
                                >
                                    <Check
                                        className="size-3.5 shrink-0"
                                        style={{ color: `var(${mod.color})` }}
                                        aria-hidden="true"
                                    />
                                    {t(feature)}
                                </li>
                            ))}
                        </ul>

                        {/* Install command */}
                        {mod.href !== null && (
                            <div className="mt-2 flex flex-col gap-2">
                                <div className="flex items-center gap-3 rounded-xl bg-gray-950 px-4 py-3 shadow-sm dark:bg-gray-900">
                                    <Terminal
                                        className="mt-0.5 size-4 shrink-0 self-start text-gray-500"
                                        aria-hidden="true"
                                    />
                                    <code className="flex-1 whitespace-pre text-sm text-green-400">
                                        {installCommand(mod, isInstalled(mod.id))}
                                    </code>
                                    <button
                                        className="cursor-pointer self-start text-gray-300 transition-colors hover:text-gray-300"
                                        onClick={copyCommand}
                                    >
                                        {copied ? (
                                            <Check className="size-4 text-green-400" />
                                        ) : (
                                            <Copy className="size-4" />
                                        )}
                                    </button>
                                </div>
                                {mod.id !== 'custom' && (
                                    <p className="text-muted-foreground pb-2 text-center text-sm">
                                        {t(
                                            'This module may require additional steps after installation, check the docs',
                                        )}
                                    </p>
                                )}
                            </div>
                        )}

                        {/* CTA */}
                        <div className="-mx-6 border-t px-6 pt-4">
                            {mod.href !== null ? (
                                <a
                                    href={mod.href}
                                    target="_blank"
                                    rel="noopener noreferrer"
                                    className="flex w-full items-center justify-center gap-2 rounded-full px-6 py-2.5 text-sm font-semibold text-white shadow-[0_5px_0_0_color-mix(in_oklch,var(--mod-color)_85%,black)] transition-all duration-200 hover:-translate-y-0.5 hover:shadow-[0_7px_0_0_color-mix(in_oklch,var(--mod-color)_85%,black)]"
                                    style={{ background: `var(${mod.color})` }}
                                >
                                    <BookOpen
                                        className="size-4"
                                        aria-hidden="true"
                                    />
                                    {t('Read the Documentation')}
                                </a>
                            ) : (
                                <span className="bg-muted/90 border-muted-foreground/20 text-muted-foreground flex w-full items-center justify-center gap-2 rounded-full border px-6 py-2.5 text-sm font-semibold">
                                    {t('Coming Soon')}
                                </span>
                            )}
                        </div>
                    </div>
                </div>
            </div>
        </>,
        document.body,
    );
}
