// resources/js/react/layouts/AppSidebar.tsx
import TenantSwitcher from '@/components/TenantSwitcher';
import NavGroup from '@/components/ui/navigation/NavGroup';
import NavUser from '@/components/ui/navigation/NavUser';
import {
    Sidebar,
    SidebarContent,
    SidebarFooter,
    SidebarHeader,
} from '@/components/ui/sidebar';
import type { User } from '@/types';
import type { Navigation } from '@/types/navigation';
import { usePage } from '@inertiajs/react';

export default function AppSidebar() {
    const page = usePage<{ navigation: Navigation; auth: { user: User } }>();

    const items = page.props.navigation?.main ?? [];
    const secondaryItems = page.props.navigation?.secondary ?? [];
    const userItems = page.props.navigation?.user ?? [];
    const user = page.props.auth?.user;

    return (
        <Sidebar variant="inset" collapsible="icon" className="bg-transparent">
            <SidebarHeader>
                <TenantSwitcher />
            </SidebarHeader>
            <SidebarContent>
                <NavGroup items={items} />
                <NavGroup items={secondaryItems} className="mt-auto" />
            </SidebarContent>
            <SidebarFooter>
                {user && <NavUser user={user} items={userItems} />}
            </SidebarFooter>
        </Sidebar>
    );
}

// resources/js/components/AppSidebar.vue
<script setup lang="ts">
import type { SidebarProps } from '@/components/ui/sidebar/index';
import {
    Sidebar,
    SidebarContent,
    SidebarFooter,
    SidebarHeader,
} from '@/components/ui/sidebar/index';
import type { User } from '@/types';
import type { Navigation } from '@/types/navigation';
import { usePage } from '@inertiajs/vue3';
import { computed } from 'vue';
import TenantSwitcher from './TenantSwitcher.vue';
import NavGroup from './ui/navigation/NavGroup.vue';
import NavUser from './ui/navigation/NavUser.vue';

withDefaults(defineProps<SidebarProps>(), {
    collapsible: 'icon',
    variant: 'inset',
    class: 'bg-transparent',
});

const page = usePage<{ navigation: Navigation; auth: { user: User } }>();

// Always show main navigation in main sidebar
const items = computed(() => page.props.navigation?.main || []);
const userItems = computed(() => page.props.navigation?.user || []);
const secondaryItems = computed(() => page.props.navigation?.secondary || []);
const user = computed(() => page.props.auth?.user);
</script>

<template>
    <Sidebar
        :variant="variant"
        :collapsible="collapsible"
        data-sidebar="sidebar"
    >
        <SidebarHeader>
            <TenantSwitcher />
        </SidebarHeader>

        <SidebarContent data-sidebar="content">
            <NavGroup :items="items" />
            <NavGroup :items="secondaryItems" class="mt-auto" />
        </SidebarContent>

        <SidebarFooter>
            <NavUser v-if="user" :user="user" :items="userItems" />
        </SidebarFooter>
    </Sidebar>
</template>
