// resources/js/react/lib/globalComponents.ts
import type { ComponentType } from 'react';

const top: ComponentType[] = [];
const bottom: ComponentType[] = [];

export function registerGlobalComponent(
    position: 'top' | 'bottom',
    component: ComponentType,
): void {
    (position === 'top' ? top : bottom).push(component);
}

export function getGlobalComponents(
    position: 'top' | 'bottom',
): ComponentType[] {
    return position === 'top' ? top : bottom;
}

// resources/js/components/GlobalComponents.vue
<script setup lang="ts">
import { getGlobalComponents } from '@/lib/globalComponents';

const { position } = defineProps<{ position: 'top' | 'bottom' }>();
const components = getGlobalComponents(position);
</script>
<template>
    <component v-for="(C, i) in components" :key="i" :is="C" />
</template>
