// resources/js/react/components/ThemeSelector.tsx
import { Button } from '@/components/ui/button';
import { ButtonGroup } from '@/components/ui/button-group';
import {
    DropdownMenu,
    DropdownMenuContent,
    DropdownMenuItem,
    DropdownMenuSub,
    DropdownMenuSubContent,
    DropdownMenuSubTrigger,
    DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import { transitionOrigin, useTheme, type Theme } from '@/hooks/useTheme';
import { useT } from '@/i18n';
import { type MouseEvent, type ReactNode } from 'react';
import IconAuto from '~icons/fluent/dark-theme-20-filled';
import IconMoon from '~icons/heroicons/moon';
import IconSun from '~icons/heroicons/sun';

const themes = [
    { code: 'light' as Theme, name: 'Light', Icon: IconSun },
    { code: 'dark' as Theme, name: 'Dark', Icon: IconMoon },
    { code: 'auto' as Theme, name: 'Device', Icon: IconAuto },
] as const;

interface ThemeSelectorProps {
    mode?: 'standalone' | 'submenu';
    triggerClass?: string;
    disableAnimation?: boolean;
    inline?: boolean;
    hideDevice?: boolean;
    fullWidth?: boolean;
    children?: ReactNode;
}

export default function ThemeSelector({
    mode = 'standalone',
    triggerClass = 'flex items-center rounded-lg p-2 text-foreground/80 transition-colors duration-200 hover:bg-accent hover:text-accent-foreground',
    disableAnimation = false,
    inline = false,
    hideDevice = false,
    fullWidth = false,
}: ThemeSelectorProps) {
    const t = useT();
    const { theme, setTheme } = useTheme();

    const visibleThemes = hideDevice
        ? themes.filter((th) => th.code !== 'auto')
        : [...themes];
    const currentTheme = themes.find((th) => th.code === theme) ?? themes[0];
    const CurrentIcon = currentTheme.Icon;

    function switchTheme(code: Theme, event: MouseEvent<HTMLElement>) {
        setTheme(code, transitionOrigin(event), !disableAnimation);
    }

    if (inline) {
        return (
            <ButtonGroup className={fullWidth ? 'w-full' : ''}>
                {visibleThemes.map(({ code, name, Icon }) => (
                    <Button
                        key={code}
                        variant={theme === code ? 'default' : 'outline'}
                        size="sm"
                        className={`${fullWidth ? 'flex-1' : ''} ${theme === code ? 'font-semibold' : ''}`}
                        data-testid={`color-mode-${code}`}
                        aria-label={t(name)}
                        onClick={(event) => switchTheme(code, event)}
                    >
                        <Icon className="size-4" />
                        {t(name)}
                    </Button>
                ))}
            </ButtonGroup>
        );
    }

    if (mode === 'standalone') {
        return (
            <DropdownMenu modal={false}>
                <DropdownMenuTrigger asChild>
                    <button
                        className={triggerClass}
                        aria-label={t('Toggle theme')}
                    >
                        <CurrentIcon className="size-5" />
                    </button>
                </DropdownMenuTrigger>
                <DropdownMenuContent align="end" className="min-w-40">
                    {visibleThemes.map(({ code, name, Icon }) => (
                        <DropdownMenuItem
                            key={code}
                            data-testid={`color-mode-${code}`}
                            onClick={(event) => switchTheme(code, event)}
                            className={
                                theme === code
                                    ? 'bg-accent text-accent-foreground'
                                    : ''
                            }
                        >
                            <Icon className="size-4" />
                            {t(name)}
                        </DropdownMenuItem>
                    ))}
                </DropdownMenuContent>
            </DropdownMenu>
        );
    }

    return (
        <DropdownMenuSub>
            <DropdownMenuSubTrigger
                data-testid="theme-selector-trigger"
                className="[&>svg]:text-muted-foreground [&>svg]:mr-2"
            >
                <CurrentIcon className="size-4" />
                {t('Theme')}
            </DropdownMenuSubTrigger>
            <DropdownMenuSubContent>
                {visibleThemes.map(({ code, name, Icon }) => (
                    <DropdownMenuItem
                        key={code}
                        data-testid={`color-mode-${code}`}
                        onClick={(event) => switchTheme(code, event)}
                        className={theme === code ? 'bg-accent' : ''}
                    >
                        <Icon className="size-4" />
                        {t(name)}
                    </DropdownMenuItem>
                ))}
            </DropdownMenuSubContent>
        </DropdownMenuSub>
    );
}

// resources/js/vue/components/ThemeSelector.vue
<script setup lang="ts">
import { revealOrigin, revealTransition } from '@js/lib/themeReveal';
import { Button } from '@/components/ui/button';
import { ButtonGroup } from '@/components/ui/button-group';
import {
    DropdownMenu,
    DropdownMenuContent,
    DropdownMenuItem,
    DropdownMenuSub,
    DropdownMenuSubContent,
    DropdownMenuSubTrigger,
    DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import { setCookie } from '@/lib/utils';
import { useColorMode } from '@vueuse/core';
import { computed, nextTick } from 'vue';
import IconAuto from '~icons/fluent/dark-theme-20-filled';
import IconMoon from '~icons/heroicons/moon';
import IconSun from '~icons/heroicons/sun';

interface Props {
    /**
     * Display mode - 'standalone' for main menu, 'submenu' for nested dropdown
     */
    mode?: 'standalone' | 'submenu';
    /**
     * Custom trigger class for standalone mode
     */
    triggerClass?: string;
    /**
     * Disable animated theme transitions using View Transitions API
     */
    disableAnimation?: boolean;
    /**
     * Render as an inline ButtonGroup instead of a dropdown
     */
    inline?: boolean;
    /**
     * Hide the Auto/Device theme option
     */
    hideDevice?: boolean;
    /**
     * Makes the inline ButtonGroup full-width with equal-width buttons
     */
    fullWidth?: boolean;
}

const props = withDefaults(defineProps<Props>(), {
    mode: 'standalone',
    triggerClass:
        'flex items-center rounded-lg p-2 text-foreground/80 transition-colors duration-200 hover:bg-accent hover:text-accent-foreground',
});

const colorMode = useColorMode({
    emitAuto: true,
    storageKey: 'appearance',
});

const themes = [
    { code: 'light', name: 'Light', icon: IconSun },
    { code: 'dark', name: 'Dark', icon: IconMoon },
    { code: 'auto', name: 'Device', icon: IconAuto },
] as const;

const visibleThemes = computed(() =>
    props.hideDevice ? themes.filter((t) => t.code !== 'auto') : [...themes],
);

const switchTheme = async (
    themeCode: 'light' | 'dark' | 'auto',
    event: MouseEvent,
) => {
    // Measured now: the dropdown closes and removes the option once it handles the click.
    const origin = revealOrigin(event.currentTarget as HTMLElement);
    setCookie('appearance', themeCode);

    if (props.disableAnimation) {
        colorMode.value = themeCode;
        return;
    }

    await revealTransition(origin, async () => {
        colorMode.value = themeCode;
        await nextTick();
    });
};

const currentTheme = computed(
    () => themes.find((theme) => theme.code === colorMode.value) || themes[0],
);
</script>

<template>
    <!-- Inline Mode (ButtonGroup) -->
    <ButtonGroup v-if="inline" :class="{ 'w-full': fullWidth }">
        <Button
            v-for="theme in visibleThemes"
            :key="theme.code"
            :variant="colorMode === theme.code ? 'default' : 'outline'"
            size="sm"
            :class="[
                { 'flex-1': fullWidth },
                { 'font-semibold': colorMode === theme.code },
            ]"
            :data-testid="`color-mode-${theme.code}`"
            :aria-label="$t(theme.name)"
            @click.capture="switchTheme(theme.code, $event)"
        >
            <component :is="theme.icon" class="size-4" />
            {{ $t(theme.name) }}
        </Button>
    </ButtonGroup>

    <!-- Standalone Mode (Landing Page) -->
    <DropdownMenu v-else-if="mode === 'standalone'" :modal="false">
        <DropdownMenuTrigger as-child>
            <button
                :class="props.triggerClass"
                :aria-label="$t('Toggle theme')"
            >
                <slot name="trigger" :current-theme="currentTheme">
                    <component :is="currentTheme.icon" class="size-5" />
                </slot>
            </button>
        </DropdownMenuTrigger>
        <DropdownMenuContent align="end" class="min-w-40">
            <DropdownMenuItem
                v-for="theme in visibleThemes"
                :key="theme.code"
                :data-testid="`color-mode-${theme.code}`"
                @click.capture="switchTheme(theme.code, $event)"
                :class="{
                    'bg-accent text-accent-foreground':
                        colorMode === theme.code,
                }"
            >
                <component :is="theme.icon" class="size-4" />
                {{ $t(theme.name) }}
            </DropdownMenuItem>
        </DropdownMenuContent>
    </DropdownMenu>

    <!-- Submenu Mode (NavUser) -->
    <DropdownMenuSub v-else>
        <DropdownMenuSubTrigger
            data-testid="theme-selector-trigger"
            class="[&>svg]:text-muted-foreground"
        >
            <slot name="submenu-trigger" :current-theme="currentTheme">
                <component :is="currentTheme.icon" class="size-4" />
                {{ $t('Theme') }}
            </slot>
        </DropdownMenuSubTrigger>
        <DropdownMenuSubContent>
            <DropdownMenuItem
                v-for="theme in visibleThemes"
                :key="theme.code"
                :data-testid="`color-mode-${theme.code}`"
                @click.capture="switchTheme(theme.code, $event)"
                :class="{ 'bg-accent': colorMode === theme.code }"
            >
                <component :is="theme.icon" class="size-4" />
                {{ $t(theme.name) }}
            </DropdownMenuItem>
        </DropdownMenuSubContent>
    </DropdownMenuSub>
</template>
