// resources/js/vue/components/ui/navigation/NavGroup.vue
<script setup lang="ts">
import { SidebarGroup, SidebarMenu } from '@/components/ui/sidebar';
import type { MenuItem } from '@/types/navigation';
import NavItem from './NavItem.vue';

defineProps<{
    items: MenuItem[];
}>();
</script>

<template>
    <SidebarGroup>
        <SidebarMenu>
            <NavItem
                v-for="item in items"
                :key="item.id || item.title"
                :item="item"
            />
        </SidebarMenu>
    </SidebarGroup>
</template>

// resources/js/react/components/ui/saucebase/navigation/NavGroup.tsx
import { SidebarGroup, SidebarMenu } from '@/components/ui/sidebar';
import type { MenuItem } from '@/types/navigation';
import NavItem from './NavItem';

interface NavGroupProps {
    items: MenuItem[];
    className?: string;
}

export default function NavGroup({ items, className }: NavGroupProps) {
    return (
        <SidebarGroup className={className}>
            <SidebarMenu>
                {items.map((item) => (
                    <NavItem key={item.id ?? item.title} item={item} />
                ))}
            </SidebarMenu>
        </SidebarGroup>
    );
}
